services:
  frontend:
    image: alecodev/poli-ci-cd-frontend
    # docker build --build-arg VITE_API_URL="http://localhost:8000/todos" -t alecodev/poli-ci-cd-frontend -f ./dockerfiles/frontend.dockerfile --target runner frontend

  backend:
    image: alecodev/poli-ci-cd-backend
    # docker build --build-arg PORT="8000" -t alecodev/poli-ci-cd-backend -f ./dockerfiles/backend.dockerfile backend
