# Simple workflow to build and deploy Docker images
name: Build & Deploy Docker image Frontend

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: ["frontend/**", "dockerfiles/frontend.dockerfile"]
    tags:
      - "v*.*.*"

# Allow one concurrent deployment
concurrency:
  group: "docker-frontend"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: alecodev/poli-ci-cd-frontend
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: dockerfiles/frontend.dockerfile
          target: runner
          build-args: |
            BASE_URL=${{ vars.BASE_URL }}
            VITE_API_URL=${{ secrets.VITE_API_URL }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
